name: Java CI with Gradle

on:
    push:
    pull_request:
        branches: [ "main" ]

jobs:
    Backend-Testing:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        services:
            postgres:
                image: postgres:16
                ports:
                    - 5433:5432
                env:
                    POSTGRES_USER: fortuna_test
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: fortuna_test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Clean Test Database Migrations With Flyway
                run: ./gradlew flywayTestDbClean
                env:
                    SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/fortuna_test
                    SPRING_DATASOURCE_USERNAME: fortuna_test
                    SPRING_DATASOURCE_PASSWORD: password

            -   name: Run Test Database Migrations With Flyway
                run: ./gradlew flywayTestDbMigrate
                env:
                    SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/fortuna_test
                    SPRING_DATASOURCE_USERNAME: fortuna_test
                    SPRING_DATASOURCE_PASSWORD: password

            # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
            # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

            -   name: Build with Gradle Wrapper
                run: ./gradlew build
                env:
                    SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/fortuna_test
                    SPRING_DATASOURCE_USERNAME: fortuna_test
                    SPRING_DATASOURCE_PASSWORD: password

            -   name: Run Backend Tests
                run: ./gradlew test

    Frontend-Testing:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        services:
            postgres:
                image: postgres:16
                ports:
                    - 5433:5432
                env:
                    POSTGRES_USER: fortuna_test
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: fortuna_test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            -   uses: actions/checkout@v4
            -   name: Run Frontend Tests
                run: ./gradlew testFrontend

    Journey-Testing:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        services:
            postgres:
                image: postgres:16
                ports:
                    - 5434:5432
                env:
                    POSTGRES_USER: fortuna_journey
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: fortuna_journey
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Clean Journey Database Migrations With Flyway
                run: ./gradlew flywayJourneyTestDbClean
                env:
                    SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5434/fortuna_journey
                    SPRING_DATASOURCE_USERNAME: fortuna_journey
                    SPRING_DATASOURCE_PASSWORD: password

            -   name: Run Journey Tests
                run: ./gradlew testJourney

    Dependency-Submission-Scan:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'

            # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
            # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
            -   name: Generate and submit dependency graph
                uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

